### ISSUE TITLE
Copied.

### ISSUE THREAD

**Issue by Mayank-1234-cmd** [Pragyanurag/Kwitter#2]
Copied from https://github.com/clintev1/Kwitter.
(Hosted @ https://notbyme-kwitter.mkcodes.repl.co/index.html)

**Comment by King-of-MC** [comment]
the reason it is copied is it maybe because its a whitehatjunior project

**Comment by Pragyanurag** [comment]
I did not copy anything just stop😡

**Comment by Pragyanurag** [comment]
> Copied from https://github.com/clintev1/Kwitter.
> (Hosted @ https://notbyme-kwitter.mkcodes.repl.co/index.html)
